### PR TITLE
Separate praefect db

### PR DESCRIPTION
**Pull request by kolomied**
*Issue #, if available:*
#62 

*Description of changes:*

- Deploy Praefect database to a separate RDS instance 
- Cleanup entry templates
- Update to the latest GitLab charts

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by gargana** [comment]
Updated the EKS QS submodule and retrying e2e tests

**Review by tlindsay42 — APPROVED** [review]

**Pull request merged**
